name: Adds all issues to the triage board

on:
  issues:
    types:
      - opened
      - transferred

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: wtg-aws
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/withthegrid/projects/19
          github-token: ${{ secrets.ROBS_PERSONAL_ACCESS_TOKEN }}
